#Our overall goal here is simply to examine how household energy usage varies over a 2-day period in February, 2007. Your task is to reconstruct the following plots below, all of which were constructed using the base plotting system.
df = read.csv("household_power_consumption.txt", sep = ";", na.strings="?", stringsAsFactors = FALSE)
df <- subset(df, df$Date == "1/2/2007" | df$Date == "2/2/2007")
df$DT <- paste(df$Date,df$Time,sep="_")
df$DT <- strptime(df$DT, "%d/%m/%Y_%H:%M:%S")
png("plot3.png")
plot(y = df$Sub_metering_1, x = df$DT, ylab="Energy sub metering",type = "n",xlab="")
lines(y = df$Sub_metering_1, x = df$DT)
lines(y = df$Sub_metering_2, x = df$DT, col = "red",type = "l")
lines(y = df$Sub_metering_3, x = df$DT, col = "blue",type = "l")
legend("topright",lty = c(1,1,1),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"))
dev.off()